/**
 * CharacterRoster.js — Personaggi Session Mode
 * ─────────────────────────────────────────────────────────────────
 * Ogni personaggio: id, name, style, feel (0=pull · 1=push), bio, img
 * style → mappa direttamente su modules.[instrument].style nel blueprint
 */

export const CHARACTER_ROSTER = {

  drums: [
    { id: 'drums_marco',  name: 'Duzzo',  style: 'brushes',       feel: 0.1,
      bio: 'Jazz intimista, brushes leggeri. Molto spazio tra le note.',
      img: 'img/icons_players/04_player_drums.png' },
    { id: 'drums_luca',   name: 'Brughi',   style: 'rock',          feel: 0.9,
      bio: 'Rock diretto, backbeat potente. Kick e snare senza fronzoli.',
      img: 'img/icons_players/04_player_drums.png' },
    { id: 'drums_davide', name: 'Jaco', style: 'cajon',         feel: 0.7,
      bio: 'Folk percussivo con cajon. Energia vivace, ritmo solido.',
      img: 'img/icons_players/04_player_drums.png' },
    { id: 'drums_carla',  name: 'Carla',  style: 'blues_shuffle', feel: 0.7,
      bio: 'Blues autentico, shuffle sincopato. Un groove che trascina.',
      img: 'img/icons_players/04_player_drums.png' },
    { id: 'drums_syd',    name: 'Syd',    style: 'jazz',          feel: 0.2,
      bio: 'Jazz trio tradizionale. Ride aperto e spazzola al pedale.',
      img: 'img/icons_players/04_player_drums.png' },
    { id: 'drums_riot',   name: 'Riot',   style: 'punk',          feel: 1.0,
      bio: 'Punk raw e velocissimo, backbeat martellante senza respiro. Zero fronzoli, tutto tirato avanti.',
      img: 'img/icons_players/04_player_drums.png' },
    { id: 'drums_fuzz',   name: 'Fuzz',   style: 'rock',          feel: 0.75,
      bio: 'Garage anni \'60, groove leggermente sciolto e sporco. Fuzz e attitude, poca precisione a bella posta.',
      img: 'img/icons_players/04_player_drums.png' },

    // ── Drum Machine ────────────────────────────────────────────
    { id: 'dm_tr8',  name: 'TR-8',  style: 'trap',    feel: 0.8,
      bio: 'Trap e hip-hop moderno. 808 sub, hi-hats veloci.',
      img: 'img/icons_players/06_player_drum_machine_seated.png' },
    { id: 'dm_lo1',  name: 'LO-1',  style: 'lo_fi',   feel: 0.4,
      bio: 'Lo-fi chill. Pattern spezzati, swing organico.',
      img: 'img/icons_players/06_player_drum_machine_seated.png' },
    { id: 'dm_e909', name: 'E-909', style: 'electro',  feel: 0.5,
      bio: 'Techno e house classica. 909 precision, step editing.',
      img: 'img/icons_players/06_player_drum_machine_seated.png' },
    { id: 'dm_pxl8', name: 'PXL-8', style: 'chiptune', feel: 0.5,
      bio: 'Groove chip quantizzato al frame, zero umanizzazione. Precisione hardware 8-bit, nessun rubato.',
      img: 'img/icons_players/06_player_drum_machine_seated.png' },

    // ── Percussionisti etnici ────────────────────────────────────
    { id: 'perc_ana',    name: 'Ana',    style: 'bossa',  feel: 0.4,
      bio: 'Bossa nova brasiliana, ritmo di samba autentico.',
      img: 'img/icons_players/05_player_percussion_conga.png' },
    { id: 'perc_miguel', name: 'Miguel', style: 'reggae', feel: 0.2,
      bio: 'Reggae one-drop, groove rilassato e pesante.',
      img: 'img/icons_players/05_player_percussion_conga.png' },
    { id: 'perc_yasmin', name: 'Yasmin', style: 'cajon',  feel: 0.6,
      bio: 'Cajon flamenco e folk, attacchi precisi.',
      img: 'img/icons_players/05_player_percussion_conga.png' },
  ],

  bass: [
    { id: 'bass_giacomo', name: 'Giacomo', style: 'walking',     feel: 0.4,
      bio: 'Walking jazz idiomatico. Chord tones, voice leading.',
      img: 'img/icons_players/01_player_bass.png' },
    { id: 'bass_antonio', name: 'Antonio', style: 'fingerstyle', feel: 0.6,
      bio: 'Funk e soul fingerstyle. Ghost notes, pocket.',
      img: 'img/icons_players/01_player_bass.png' },
    { id: 'bass_james',   name: 'James',   style: 'slap',        feel: 0.9,
      bio: 'Slap aggressivo, attacchi percussivi. Groove immediato.',
      img: 'img/icons_players/01_player_bass.png' },
    { id: 'bass_bruno',   name: 'Bruno',   style: 'fretless',    feel: 0.2,
      bio: 'Fretless morbido, glissandi. Jazz-fusion e world.',
      img: 'img/icons_players/01_player_bass.png' },
  ],

  guitar: [
    { id: 'acgtr_francesco', name: 'Francesco', style: 'fingerpicking', feel: 0.3,
      bio: 'Travis picking idiomatico, basso polifonico.',
      img: 'img/icons_players/07_player_guitar_acoustic_singer.png' },
    { id: 'acgtr_giulia',    name: 'Giulia',    style: 'strumming',     feel: 0.7,
      bio: 'Strumming folk aperto, ritmico e luminoso.',
      img: 'img/icons_players/07_player_guitar_acoustic_singer.png' },
    { id: 'acgtr_matteo',    name: 'Matteo',    style: 'arpeggio',      feel: 0.4,
      bio: 'Arpeggio classico, melodia e basso intrecciati.',
      img: 'img/icons_players/07_player_guitar_acoustic_singer.png' },
    { id: 'elgtr_ricky',     name: 'Ricky',     style: 'powerchord',    feel: 1.0,
      bio: 'Rock diretto, powerchords, ritmo di ferro.',
      img: 'img/icons_players/12_player_guitar_electric.png' },
    { id: 'elgtr_alex',      name: 'Alex',      style: 'riff',          feel: 0.8,
      bio: 'Riff melodici, singola nota espressiva.',
      img: 'img/icons_players/12_player_guitar_electric.png' },
  ],

  piano: [
    { id: 'piano_sofia',  name: 'Sofia',  style: 'ballad',       feel: 0.2,
      bio: 'Ballad lirica, accordi larghi, respiro tra le note.',
      img: 'img/icons_players/02_player_piano_classical.png' },
    { id: 'kb_theo',      name: 'Theo',   style: 'comping',      feel: 0.4,
      bio: 'Comping jazz, shell voicings. Swing e molto spazio.',
      img: 'img/icons_players/03_player_keyboard_standing.png' },
    { id: 'piano_chiara', name: 'Chiara', style: 'new_age_flow', feel: 0.2,
      bio: 'New age fluente, armonie sospese, melodia libera.',
      img: 'img/icons_players/02_player_piano_classical.png' },
    { id: 'kb_elena',     name: 'Elena',  style: 'freely',       feel: 0.5,
      bio: 'Improvvisazione libera jazz-soul. Mai due bar uguali.',
      img: 'img/icons_players/11_player_keyboard_seated_female.png' },
    { id: 'kb_kwame',     name: 'Kwame',  style: 'broken_chords', feel: 0.7,
      bio: 'R&B moderno, broken chords. Groove e colore.',
      img: 'img/icons_players/03_player_keyboard_standing.png' },
    { id: 'kb_nina',      name: 'Nina',   style: 'hip_hop_keys', feel: 0.8,
      bio: 'Stabs R&B, chord tones sincopati. Vibe urban.',
      img: 'img/icons_players/11_player_keyboard_seated_female.png' },
  ],

  ensemble: [
    { id: 'str_ensemble', name: 'Archi',  style: 'strings',   feel: 0.4,
      bio: 'Ensemble d\'archi, voice leading automatizzato.',
      img: 'img/icons_players/08_player_strings_trio.png' },
    { id: 'str_camera',   name: 'Camera', style: 'chamber',   feel: 0.3,
      bio: 'Quartetto intimo, contrappunto fine.',
      img: 'img/icons_players/08_player_strings_trio.png' },
    { id: 'brs_ottoni',   name: 'Ottoni', style: 'brass',     feel: 0.8,
      bio: 'Sezione ottoni jazz, thick e punchy.',
      img: 'img/icons_players/09_player_brass_duo.png' },
    { id: 'brs_legni',    name: 'Legni',  style: 'woodwinds', feel: 0.5,
      bio: 'Sezione legni, flute e oboe eterei.',
      img: 'img/icons_players/10_player_woodwinds_duo.png' },
  ],
};
